name: free_open_ocean
description: "Free Open Ocean"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2

environment:
  sdk: ^3.10.1
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  package_info_plus: ^9.0.0
  grpc: ^5.1.0
  protobuf: ^6.0.0
  http: ^1.2.1
  go_router: ^17.0.1
  free_open_ocean_grpc:
    git:
      url: git@github.com:dmRusakov/FreeOpenOcean-GRPC.git
      ref: main
      path: grpc-contracts/dart
    version: ^0.1.27
  universal_html: ^2.2.4
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/flags/
